In [59]:
# Handling date and time in data set

In [60]:
import pandas as pd
time= pd.read_csv(r"C:\Users\sus\Downloads\messages.csv")
date=pd.read_csv(r"C:\Users\sus\Downloads\orders.csv")

In [61]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [62]:
date

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [63]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [64]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

# woking with date

In [65]:
date["date"]= pd.to_datetime(date["date"])

In [66]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [67]:
# extract year
date["date_year"]= date['date'].dt.year

In [68]:
date

          date  product_id  city_id  orders  date_year
0   2019-12-10        5628       25       3       2019
1   2018-08-15        3646       14     157       2018
2   2018-10-23        1859       25       1       2018
3   2019-08-17        7292       25       1       2019
4   2019-01-06        4344       25       3       2019
..         ...         ...      ...     ...        ...
995 2018-10-08         255       13       1       2018
996 2018-12-06        5521        7       1       2018
997 2019-05-07         487       26      14       2019
998 2019-03-03        1503       21       2       2019
999 2019-10-15        6371        7      22       2019

[1000 rows x 5 columns]

In [69]:
date["date_day"]=date["date"].dt.day

In [70]:
date.head(2)

        date  product_id  city_id  orders  date_year  date_day
0 2019-12-10        5628       25       3       2019        10
1 2018-08-15        3646       14     157       2018        15

In [71]:
date["day_of_week"]= date["date"].dt.day_name()

In [72]:
date.head(1)

        date  product_id  city_id  orders  date_year  date_day day_of_week
0 2019-12-10        5628       25       3       2019        10     Tuesday

In [73]:
import numpy as np
date["date_is_weekend"] = np.where(date["day_of_week"].isin(["Sunday", "Saturday"]), 1, 0)

In [74]:
date

,date,product_id,city_id,orders,date_year,date_day,day_of_week,date_is_weekend
0,2019-12-10,5628,25,3,2019,10,Tuesday,0
1,2018-08-15,3646,14,157,2018,15,Wednesday,0
2,2018-10-23,1859,25,1,2018,23,Tuesday,0
3,2019-08-17,7292,25,1,2019,17,Saturday,1
4,2019-01-06,4344,25,3,2019,6,Sunday,1
...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,8,Monday,0
996,2018-12-06,5521,7,1,2018,6,Thursday,0
997,2019-05-07,487,26,14,2019,7,Tuesday,0
998,2019-03-03,1503,21,2,2019,3,Sunday,1
999,2019-10-15,6371,7,22,2019,15,Tuesday,0

In [75]:
date["date_week"] = date["date"].dt.isocalendar().week

In [76]:
date

,date,product_id,city_id,orders,date_year,date_day,day_of_week,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,10,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,15,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,23,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,17,Saturday,1,33
4,2019-01-06,4344,25,3,2019,6,Sunday,1,1
...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,8,Monday,0,41
996,2018-12-06,5521,7,1,2018,6,Thursday,0,49
997,2019-05-07,487,26,14,2019,7,Tuesday,0,19
998,2019-03-03,1503,21,2,2019,3,Sunday,1,9
999,2019-10-15,6371,7,22,2019,15,Tuesday,0,42

In [77]:
date["quarter"]=date["date"].dt.quarter
date["semester"]=np.where(date["quarter"].isin([1,2]),1,2)

In [78]:
date

,date,product_id,city_id,orders,date_year,date_day,day_of_week,date_is_weekend,date_week,quarter,semester
0,2019-12-10,5628,25,3,2019,10,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,15,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,23,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,17,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,6,Sunday,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,8,Monday,0,41,4,2
996,2018-12-06,5521,7,1,2018,6,Thursday,0,49,4,2
997,2019-05-07,487,26,14,2019,7,Tuesday,0,19,2,1
998,2019-03-03,1503,21,2,2019,3,Sunday,1,9,1,1
999,2019-10-15,6371,7,22,2019,15,Tuesday,0,42,4,2

In [79]:
# extract time elapsed between dates 
import datetime
today= datetime.datetime.today()
today

datetime.datetime(2025, 8, 2, 21, 50, 3, 740827)

In [80]:
today-date["date"]

0     2062 days 21:50:03.740827
1     2544 days 21:50:03.740827
2     2475 days 21:50:03.740827
3     2177 days 21:50:03.740827
4     2400 days 21:50:03.740827
                 ...
995   2490 days 21:50:03.740827
996   2431 days 21:50:03.740827
997   2279 days 21:50:03.740827
998   2344 days 21:50:03.740827
999   2118 days 21:50:03.740827
Name: date, Length: 1000, dtype: timedelta64[ns]

In [81]:
(today-date["date"]).dt.days

0      2062
1      2544
2      2475
3      2177
4      2400
       ...
995    2490
996    2431
997    2279
998    2344
999    2118
Name: date, Length: 1000, dtype: int64

In [82]:
# months passed
months_passed = (today.year - date["date"].dt.year) * 12 + (today.month - date["date"].dt.month)
date["months_passed"] = months_passed

In [83]:
date

,date,product_id,city_id,orders,date_year,date_day,day_of_week,date_is_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,5628,25,3,2019,10,Tuesday,0,50,4,2,68
1,2018-08-15,3646,14,157,2018,15,Wednesday,0,33,3,2,84
2,2018-10-23,1859,25,1,2018,23,Tuesday,0,43,4,2,82
3,2019-08-17,7292,25,1,2019,17,Saturday,1,33,3,2,72
4,2019-01-06,4344,25,3,2019,6,Sunday,1,1,1,1,79
...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,8,Monday,0,41,4,2,82
996,2018-12-06,5521,7,1,2018,6,Thursday,0,49,4,2,80
997,2019-05-07,487,26,14,2019,7,Tuesday,0,19,2,1,75
998,2019-03-03,1503,21,2,2019,3,Sunday,1,9,1,1,77
999,2019-10-15,6371,7,22,2019,15,Tuesday,0,42,4,2,70

In [84]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [85]:
time.drop("msg", axis=1, inplace=True)  # ✅ correct

In [86]:
time

                    date
0    2013-12-15 00:50:00
1    2014-04-29 23:40:00
2    2012-12-30 00:21:00
3    2014-11-28 00:31:00
4    2013-10-26 23:11:00
..                   ...
995  2012-03-16 00:50:00
996  2014-01-23 23:14:00
997  2012-10-15 23:37:00
998  2012-06-21 23:34:00
999  2014-06-19 23:25:00

[1000 rows x 1 columns]

In [87]:
time["date"]=pd.to_datetime(time["date"])

In [88]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [89]:
time["hour"]=time["date"].dt.hour
time["min"]=time["date"].dt.minute
time["sec"]=time["date"].dt.second

In [90]:
time.head(1)

                 date  hour  min  sec
0 2013-12-15 00:50:00     0   50    0

In [91]:
time["time"]=time["date"].dt.time

In [92]:
time

                   date  hour  min  sec      time
0   2013-12-15 00:50:00     0   50    0  00:50:00
1   2014-04-29 23:40:00    23   40    0  23:40:00
2   2012-12-30 00:21:00     0   21    0  00:21:00
3   2014-11-28 00:31:00     0   31    0  00:31:00
4   2013-10-26 23:11:00    23   11    0  23:11:00
..                  ...   ...  ...  ...       ...
995 2012-03-16 00:50:00     0   50    0  00:50:00
996 2014-01-23 23:14:00    23   14    0  23:14:00
997 2012-10-15 23:37:00    23   37    0  23:37:00
998 2012-06-21 23:34:00    23   34    0  23:34:00
999 2014-06-19 23:25:00    23   25    0  23:25:00

[1000 rows x 5 columns]

In [93]:
today-time["date"]

0     4248 days 21:00:03.740827
1     4112 days 22:10:03.740827
2     4598 days 21:29:03.740827
3     3900 days 21:19:03.740827
4     4297 days 22:39:03.740827
                 ...
995   4887 days 21:00:03.740827
996   4208 days 22:36:03.740827
997   4673 days 22:13:03.740827
998   4789 days 22:16:03.740827
999   4061 days 22:25:03.740827
Name: date, Length: 1000, dtype: timedelta64[ns]

In [94]:
#in secs
(today-time["date"])/np.timedelta64(1,"s")

0      3.671028e+08
1      3.553566e+08
2      3.973445e+08
3      3.370367e+08
4      3.713423e+08
           ...
995    4.223124e+08
996    3.636526e+08
997    4.038272e+08
998    4.138498e+08
999    3.509511e+08
Name: date, Length: 1000, dtype: float64

In [95]:
#in minutes
(today-time["date"])/np.timedelta64(1,"m")

0      6.118380e+06
1      5.922610e+06
2      6.622409e+06
3      5.617279e+06
4      6.189039e+06
           ...
995    7.038540e+06
996    6.060876e+06
997    6.730453e+06
998    6.897496e+06
999    5.849185e+06
Name: date, Length: 1000, dtype: float64

In [ ]:
#in